version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: wifiscout-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:z
      - ./static:/static:Z
      - ../WiFiDePict:/WiFiDePict:z
    depends_on:
      - web
  web:
    build: .
    container_name: wifiscout-gunicorn
    dns: 8.8.8.8
    volumes:
      - ./db:/app/db:Z
      - ./static:/app/static:z
      - ../WiFiSCORE:/WiFiSCORE:Z
      - ../WiFiDePict:/WiFiDePict:z
    expose:
      - "8000"
