# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:00
from __future__ import unicode_literals

import devices.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='devices.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('wifi_signature', models.CharField(max_length=1000)),
                ('mac_vendor', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=devices.models.device_directory_path)),
                ('image_url', models.CharField(blank=True, default='', max_length=250)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Category')),
            ],
        ),
    ]
