# Generated by Django 2.1.5 on 2019-02-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20190207_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='signature_24',
            field=models.ManyToManyField(blank=True, related_name='device_signature_24', to='devices.Signature'),
        ),
        migrations.AlterField(
            model_name='device',
            name='signature_5',
            field=models.ManyToManyField(blank=True, related_name='device_signature_5', to='devices.Signature'),
        ),
    ]
