# Generated by Django 2.1.5 on 2019-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20190211_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='wifi_signature',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
