# Generated by Django 2.1.5 on 2019-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20190211_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='chipset',
            field=models.CharField(default='', max_length=255),
        ),
    ]
