# Generated by Django 2.1.5 on 2019-02-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_chipset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='chipset',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
